version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stock-trend-analyzer"
s3_prefix = "stock-trend-analyzer"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FMPApiKey=\"YOUR_API_KEY_HERE\""
image_repositories = []
resolve_s3 = true

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.global.parameters]
region = "eu-west-1"
