version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stock-trend-analyzer"
s3_prefix = "stock-trend-analyzer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FMPApiKey=\"YOUR_API_KEY_HERE\""
image_repositories = []

[default.build]
[default.build.parameters]
cached = true
parallel = true
